name = "api_zeng"
compatibility_date = "2025-02-04"

compatibility_flags = ["nodejs_compat"]

main = "functions/_worker.ts" 

# Habilitar Workers Logs
[observability.logs]
enabled = true


[vars]
NODE_ENV = "development"

[[d1_databases]]
binding = "db_zeng"
database_name = "db_zeng_d1"
database_id = "791b5ebd-c107-4134-8bb9-755421a929db"

[[r2_buckets]]
binding = "r2_zeng"
bucket_name = "zeng20613786946"

[dev]
port = 8788
local = true